services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      env_file:
        - .env
      ports:
        - 3306:3306
      restart: always
