services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    env_file:
      - .env
    ports:
      - 3306:3306
    healthcheck:
      test: "mysql -u${DB_USER} -p${DB_PASSWORD} --execute 'SELECT 1;'"
      interval: 5s
      timeout: 30s
      retries: 5
    restart: always
